
---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: mutating-webhook-configuration
webhooks:
- clientConfig:
    caBundle: Cg==
    service:
      name: webhook-service
      namespace: system
      path: /mutate-terminus-infoblox-com-v1-featureflag
  failurePolicy: Fail
  name: mfeatureflag.kb.io
  rules:
  - apiGroups:
    - terminus.infoblox.com
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - featureflags
- clientConfig:
    caBundle: Cg==
    service:
      name: webhook-service
      namespace: system
      path: /mutate-terminus-infoblox-com-v1-featureflagoverride
  failurePolicy: Fail
  name: mfeatureflagoverride.kb.io
  rules:
  - apiGroups:
    - terminus.infoblox.com
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - featureflagoverrides

---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- clientConfig:
    caBundle: Cg==
    service:
      name: webhook-service
      namespace: system
      path: /validate-terminus-infoblox-com-v1-featureflag
  failurePolicy: Fail
  name: vfeatureflag.kb.io
  rules:
  - apiGroups:
    - terminus.infoblox.com
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - featureflags
- clientConfig:
    caBundle: Cg==
    service:
      name: webhook-service
      namespace: system
      path: /validate-terminus-infoblox-com-v1-featureflagoverride
  failurePolicy: Fail
  name: vfeatureflagoverride.kb.io
  rules:
  - apiGroups:
    - terminus.infoblox.com
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - featureflagoverrides
