{{ $appName := .Chart.Name }}
{{- if .Values.authz.enabled -}}
{{ $namespace := .Release.Namespace }}
{{ $authzNamespace := .Values.authz.namespace }}
apiVersion: authz.infoblox.com/v1
kind: RoleAssignment
metadata:
  name: feature-flags
  namespace: {{ $namespace }}
  labels:
    authz-namespace: {{ $authzNamespace }}
    application: atlas.feature.flag
subjectgroups:
  - interservice
roles:
  - {{ $namespace }}-users-role
resourcegroups:
  - all-service
---
apiVersion: authz.infoblox.com/v1
kind: Role
metadata:
  name: {{ $namespace }}-users-role
  namespace: {{ $namespace }}
  labels:
    authz-namespace: {{ $authzNamespace }}
    application: atlas.feature.flag
permissions:
  - {{ $namespace }}-users-permission
---
apiVersion: authz.infoblox.com/v1
kind: Permission
metadata:
  name: {{ $namespace }}-users-permission
  namespace: {{ $namespace }}
  labels:
    authz-namespace: {{ $authzNamespace }}
    application: atlas.feauture.flag
endpoints:
  - AtlasFeatureFlag.GetVersion
  - AtlasFeatureFlag.List
  - AtlasFeatureFlag.Read
---
apiVersion: authz.infoblox.com/v1
kind: Endpointset
metadata:
  name: {{ $appName }}-read-endpoint-set
  namespace: {{ $namespace }}
  labels:
    authz-namespace: {{ $authzNamespace }}
    application: atlas.feature.flag
permissions:
  - default
endpoints:
  - AtlasFeatureFlag.GetVersion
  - AtlasFeatureFlag.List
  - AtlasFeatureFlag.Read
---
apiVersion: authz.infoblox.com/v1
kind: Feature
metadata:
  name: feature-flags
  namespace: {{ $namespace }}
  labels:
    authz-namespace: {{ $authzNamespace }}
    application: atlas.feature.flag
bypassLicensing: true
endpoints:
  - AtlasFeatureFlag.GetVersion
  - AtlasFeatureFlag.List
  - AtlasFeatureFlag.Read
  {{ end }}