app:
  id: atlas.feature.flag
server:
  address: 0.0.0.0
  port: 9090
gateway:
  enable: true
  address: 0.0.0.0
  port: 8080
  endpoint: /terminus/v1/
  swaggerFile: ./www/service.swagger.json
atlas.authz:
  enable: false
  address: themis.authz
  port: 5555
atlas.audit:
  enable: false
  address: atlas.audit
  port: 5555
atlas.tagging:
  enable: false
  address: atlas.tagging
  port: 5555
internal:
  enable: true
  address: 0.0.0.0
  port: 8081
  health: /healthz
  readiness: /ready
config:
  source: deploy
  secret.file: 
logging:
  level: debug