apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: feature-flag-cluster-role
rules:
  - apiGroups: ["apiextensions.k8s.io"]
    resources: ["certificates", "issuers", "customresourcedefinitions"]
    verbs: ["get", "list", "watch", "create", "delete", "update", "patch", "deletecollection"]
  - apiGroups: ["terminus.infoblox.com"]
    resources: ["featureflags", "featureflagoverrides"]
    verbs: ["get", "list", "watch", "create", "delete", "update", "patch", "deletecollection"]
---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: feature-flag-cluster-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: feature-flag-cluster-role
subjects:
  - kind: ServiceAccount
    name: {{ .Values.serviceAccount.name }}
    namespace: {{ .Release.Namespace }}
