apiVersion: spacecontroller.infoblox-cto.github.com/v1alpha1
kind: Space
metadata:
  labels:
    app: {{ .Chart.Name }}
  name: infobloxctokey
  namespace: {{ .Release.Namespace }}
spec:
  path: /image-pull/infobloxctokey
  secretName: infobloxctokey
  secrets:
    config: VAULT
  type: kubernetes.io/dockerconfigjson
