# Default values for feature-flag.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: infobloxcto/atlas.feature.flag
  tag: # defaults to .Chart.Version
  pullPolicy: Always

serviceAccount:
  name: feature-flag

debugLevel: info

nameOverride: ""
fullnameOverride: ""

service:
  ports:
    grpc:
      protocol: TCP
      port: 9090
    http:
      protocol: TCP
      port: 8080
    health:
      protocol: TCP
      port:  8081

ingress:
  enabled: true
  tls:
    enabled: true

host:
  csp:
    domain: "csp.infoblox.com"

prometheus:
  scrape: true

authz:
  enabled: true
  namespace: "authz"
  policy:
    serviceName: "themis"
    port: 80

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
